.\"     Title: \fBlqr_vmap_internal_dump\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_VMAP_INTERNAL_DUMP\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_vmap_internal_dump \- dump an LqrVMap objects into an LqrCarver object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 33
.BI "LqrRetVal lqr_vmap_internal_dump(LqrCarver*\ " "carver" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_vmap_internal_dump\fR
dumps the current visibility map of the
LqrCarver
object pointed to by
\fIcarver\fR
internally to it, attaching it to the same
LqrVMapList
object list as the one used for automatic dumping (as activated by
\fBlqr_carver_set_dump_vmaps\fR(3)\&.
.SH "SEE ALSO"
.PP

\fBLqrRetVal\fR(3), \fBlqr_vmap_dump\fR(3), \fBlqr_vmap_load\fR(3), \fBlqr_carver_set_dump_vmaps\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
