.\"     Title: \fBlqr_progress_set_init\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_PROGRESS_SET_INIT\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_progress_set_init \- execude custom code before each rescaling operation
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 32
.BI "LqrRetVal lqr_progress_set_init(LqrProgress*\ " "p" ", LqrProgressFuncInit\ " "init_func" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_progress_set_init\fR
sets the hook
\fIinit_func\fR
to the
LqrProgress
object pointed to by
\fIp\fR\&.
.PP
The function
\fIinit_func\fR
is of type
LqrProgressFuncInit, whose prototype is defined by:
.sp
.RS 4
.nf
typedef LqrRetVal (*LqrProgressFuncInit) (const gchar* init_message);
                        
.fi
.RE
.sp
Each time that the function
\fBlqr_carver_resize\fR(3)
performs a rescale operation (recall that it can perform more than one rescale operation at each call) this function will be called first, with a string argument passed through the parameter
\fIinit_message\fR, which is different for horizontal and vertical rescalings\&.
.PP
The message arguments can be set with the functions
\fBlqr_progress_set_init_width_message\fR(3)
and
\fBlqr_progress_set_init_height_message\fR(3)\&.
.PP
The default values for newly created
LqrProgress
objects are:
.PP
Horizontal:
.RS 4

"Resizing width\&.\&.\&."
.RE
.PP
Vertical:
.RS 4

"Resizing height\&.\&.\&."
.RE
.SH "RETURN VALUE"
.PP
The return value follows the Liquid Rescale library signalling system\&.
.SH "SEE ALSO"
.PP

\fBLqrRetVal\fR(3), \fBlqr_progress_new\fR(3), \fBlqr_progress_set_update\fR(3), \fBlqr_progress_set_end\fR(3), \fBlqr_progress_set_init_width_message\fR(3), \fBlqr_progress_set_init_height_message\fR(3), \fBlqr_progress_set_end_width_message\fR(3), \fBlqr_progress_set_end_height_message\fR(3), \fBlqr_progress_set_update_step\fR(3), \fBlqr_carver_set_progress\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
