.\"     Title: \fBlqr_vmap_list_next\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_VMAP_LIST_NEXT\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_vmap_list_next \- advance the LqrVMapList object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 31
.BI "LqrVMapList lqr_vmap_list_next(LqrVMapList*\ " "list" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_vmap_list_next\fR
returns a pointer the next dumped
LqrVMap
object in
\fIlist\fR, or
NULL
if the list has reached the end\&.
.SH "SEE ALSO"
.PP

\fBlqr_vmap_list_start\fR(3), \fBlqr_vmap_list_current\fR(3), \fBlqr_vmap_list_foreach\fR(3), \fBlqr_vmap_internal_dump\fR(3), \fBlqr_carver_set_dump_vmaps\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
