.\"     Title: \fBlqr_carver_get_col_depth\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_CARVER_GET_COL_DEPTH\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_carver_get_col_depth \- get the colour depth of a LqrCarver object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 37
.BI "LqrColDepth lqr_carver_get_col_depth(LqrCarver*\ " "carver" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_carver_get_col_depth\fR
returns the colour depth of the image contained in the
LqrCarver
object pointed to by
\fIcarver\fR\&.
.SH "SEE ALSO"
.PP

\fBLqrColDepth\fR(3), \fBlqr_carver_get_width\fR(3), \fBlqr_carver_get_height\fR(3), \fBlqr_carver_get_ref_width\fR(3), \fBlqr_carver_get_ref_height\fR(3), \fBlqr_carver_get_channels\fR(3), \fBlqr_carver_get_enl_step\fR(3), \fBlqr_carver_get_orientation\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
