.\"     Title: \fBlqr_carver_scan_reset\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_CARVER_SCAN_RESET\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_carver_scan_reset \- reset the readout cursor of a multi-size image
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 27
.BI "void lqr_carver_scan_reset(LqrCarver*\ " "carver" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_carver_scan_reset\fR
resets the readout pointer associated with the
LqrCarver
object pointed to by
\fIcarver\fR
to the start of the image\&. (Normally, calling this function isn\'t needed, as the pointer is reset automatically whenever an operation is performed or once a readout has completed\&.)
.SH "SEE ALSO"
.PP

\fBlqr_carver_scan\fR(3), \fBlqr_carver_scan_by_row\fR(3), \fBlqr_carver_scan_line\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
