.\"     Title: \fBlqr_progress_set_update\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_PROGRESS_SET_UPDATE\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_progress_set_update \- execude custom code at regular steps during each rescaling operation
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 34
.BI "LqrRetVal lqr_progress_set_update(LqrProgress*\ " "p" ", LqrProgressFuncUpdate\ " "update_func" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_progress_set_update\fR
sets the hook
\fIupdate_func\fR
to the
LqrProgress
object pointed to by
\fIp\fR\&.
.PP
The function
\fIupdate_func\fR
is of type
LqrProgressFuncUpdate, whose prototype is defined by:
.sp
.RS 4
.nf
typedef LqrRetVal (*LqrProgressFuncUpdate) (gdouble completion_percentage);
                        
.fi
.RE
.sp
Each time that the function
\fBlqr_carver_resize\fR(3)
performs a rescale operation (recall that it can perform more than one rescale operation at each call) this function will be called at regular intervale, with the current completion percentage
\fIcompletion_percentage\fR
as an argument\&.
.PP
The update step can be set with the function
\fBlqr_progress_set_update_step\fR(3)\&.
.SH "RETURN VALUE"
.PP
The return value follows the Liquid Rescale library signalling system\&.
.SH "SEE ALSO"
.PP

\fBLqrRetVal\fR(3), \fBlqr_progress_new\fR(3), \fBlqr_progress_set_init\fR(3), \fBlqr_progress_set_end\fR(3), \fBlqr_progress_set_init_width_message\fR(3), \fBlqr_progress_set_init_height_message\fR(3), \fBlqr_progress_set_end_width_message\fR(3), \fBlqr_progress_set_end_height_message\fR(3), \fBlqr_progress_set_update_step\fR(3), \fBlqr_carver_set_progress\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
