.\"     Title: \fBlqr_carver_scan_line\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_CARVER_SCAN_LINE\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_carver_scan_line, lqr_carver_scan_line_ext \- read out a multi-size image one line at a time
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 30
.BI "gboolean lqr_carver_scan_line(LqrCarver*\ " "carver" ", gint*\ " "n" ", guchar**\ " "rgb" ");"
.HP 34
.BI "gboolean lqr_carver_scan_line_ext(LqrCarver*\ " "carver" ", gint*\ " "n" ", void**\ " "rgb" ");"
.SH "DESCRIPTION"
.PP
The functions
\fBlqr_carver_scan_line\fR
and
\fBlqr_carver_scan_line_ext\fR
are used to read out the multi\-size image contained in the
LqrCarver
object pointed to by
\fIcarver\fR
one line at a time\&. They store the line number (row or column) in the variable pointed to by
\fIn\fR
and the colour values in the array pointed to by
\fIrgb\fR; then they move the readout pointer to the next line, or they reset it if the end of the image is reached\&.
.PP
The first one must only be used on the
LqrCarver
objects created with
\fIlqr_carver_new\fR, i\&.e\&. with 8\-bit images, while the second one is general, but the
\fIrgb\fR
pointer must be cast to the appropriate type to be used (i\&.e pass the address of a pointer to
void
to the function
\fBlqr_carver_scan_line_ext\fR, then cast it to a pointer of the appropriate type and use this last one for reading the output)\&.
.PP
Use the function
\fBlqr_carver_scan_by_row\fR(3)
before calling these to know whether your image will be scanned by row or by column\&.
.SH "RETURN VALUE"
.PP
These functions return
TRUE
in case the readout is successful and the end of the image was not reached,
FALSE
otherwise\&. If
\fBlqr_carver_scan_line\fR
is called over a non\-8\-bit
LqrCarver
object, it will return
FALSE\&.
.SH "SEE ALSO"
.PP

\fBLqrColDepth\fR(3), \fBlqr_carver_scan_reset\fR(3), \fBlqr_carver_scan\fR(3), \fBlqr_carver_scan_by_row\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
