.\"     Title: \fBlqr_vmap_get_orientation\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_VMAP_GET_ORIENTATION\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_vmap_get_orientation \- get the orientation of an LqrVMap object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 30
.BI "gint lqr_vmap_get_orientation(LqrVMap*\ " "vmap" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_vmap_get_orientation\fR
returns the orientation of the
LqrVMap
object pointed to by
\fIvmap\fR, which is
0
for horizontally oriented maps,
1
for vertically oriented ones\&.
.PP
See the
LqrVMap
objects format description in the page for
LqrVMap constructor and destructor\&.
.SH "SEE ALSO"
.PP

\fBlqr_vmap_new\fR(3), \fBlqr_vmap_get_data\fR(3), \fBlqr_vmap_get_depth\fR(3), \fBlqr_vmap_get_width\fR(3), \fBlqr_vmap_get_height\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
