.\"     Title: \fBlqr_carver_get_height\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 21 Oct 2008
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.2.0 API (1:0:1)
.\"
.TH "\FBLQR_CARVER_GET_HEIGHT\FR" "3" "21 Oct 2008" "LqR library 0.2.0 API (1:0:1)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_carver_get_height - get the current height of a LqrCarver object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\.h>
.fi
.ft
.HP 27
.BI "gint lqr_carver_get_height(LqrCarver*\ " "carver" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_carver_get_height\fR
returns the current height of the image contained in the
LqrCarver
object pointed to by
\fIcarver\fR, in pixel units\.
.SH "SEE ALSO"
.PP

\fBlqr_carver_get_width\fR(3), \fBlqr_carver_get_channels\fR(3), \fBlqr_carver_get_col_depth\fR(3), \fBlqr_carver_get_enl_step\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2008 Carlo Baldassi
.br
