.\"     Title: \fBlqr_vmap_get_data\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_VMAP_GET_DATA\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_vmap_get_data \- get varous LqrVMap object quantities
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 24
.BI "gint* lqr_vmap_get_data(LqrVMap*\ " "vmap" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_vmap_get_data\fR
returns an array with the data stored into the
LqrVMap
object pointed to by
\fIvmap\fR, ordered first by row, then by column\&.
.PP
Reading the data requires retrieval of the other quantities, through the functions
\fBlqr_vmap_get_depth\fR(3),
\fBlqr_vmap_get_width\fR(3),
\fBlqr_vmap_get_height\fR(3)
and
\fBlqr_vmap_get_orientation\fR(3)\&.
.PP
See the
LqrVMap
objects format description in the page for
\fBlqr_vmap_new\fR(3)\&.
.SH "SEE ALSO"
.PP

\fBlqr_vmap_new\fR(3), \fBlqr_vmap_get_depth\fR(3), \fBlqr_vmap_get_width\fR(3), \fBlqr_vmap_get_height\fR(3), \fBlqr_vmap_get_orientation\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
