.\"     Title: \fBlqr_carver_set_use_cache\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQR_CARVER_SET_USE_CACHE\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lqr_carver_set_use_cache \- enable/disable LqrCarver object cache
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <lqr\&.h>
.fi
.ft
.HP 30
.BI "void lqr_carver_set_use_cache(LqrCarver*\ " "carver" ", gboolean\ " "use_cache" ");"
.SH "DESCRIPTION"
.PP
The function
\fBlqr_carver_set_use_cache\fR
can be used to disable or enable the cache for the
LqrCarver
object pointed to by
\fIcarver\fR\&.
.PP
By default, the caching is on\&.
.SH "SEE ALSO"
.PP

\fBlqr_carver_set_enl_step\fR(3), \fBlqr_carver_set_resize_order\fR(3), \fBlqr_carver_set_dump_vmaps\fR(3), \fBlqr_carver_set_side_switch_frequency\fR(3), \fBlqr_carver_set_progress\fR(3), \fBlqr_carver_set_preserve_input_image\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
