.\"     Title: \fBLqrColDepth\fR
.\"    Author: Carlo Baldassi
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10 Maj 2009
.\"    Manual: LqR library API reference
.\"    Source: LqR library 0.4.1 API (3:1:3)
.\"
.TH "\FBLQRCOLDEPTH\FR" "3" "10 Maj 2009" "LqR library 0.4.1 API (3:1:3)" "LqR library API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
LqrColDepth \- carver objects colour depth specification
.SH "DESCRIPTION"
.PP
The default
LqrCarver
object constructor
\fBlqr_carver_new\fR
uses a colour depth of 8 bits per channel, and therefore its input must be an array of
\fBunsigned char\fRs\&. However, the
LqrCarver
objects can handle images of grater colour depth, if they are created with the
\fBlqr_carver_new_ext\fR
constructor\&. The possible colour depths are specified through variables of type
\fBLqrColDepth\fR, which is an enum type; its possible values, and the type of the input buffer associated with them, are:
.PP
LQR_COLDEPTH_8I
.RS 4
use type
\fBguchar\fR
(8 bit unsigned integers) \- the default
.RE
.PP
LQR_COLDEPTH_16I
.RS 4
use type
\fBguint16\fR
(16 bit unsigned integers)
.RE
.PP
LQR_COLDEPTH_32F
.RS 4
use type
\fBgfloat\fR
(32 bit floating point)
.RE
.PP
LQR_COLDEPTH_64F
.RS 4
use type
\fBgdouble\fR
(64 bit floating point)
.RE
.PP
These values are also relevant when reading out a
LqrCarver
object with the functions
\fBlqr_carver_scan_ext\fR
or
\fBlqr_carver_scan_line_ext\fR, since the readout buffer must be cast to the appropriate type to be actually read\&.
.PP
The colour depth of an
LqrCarver
object can be obtained with the function
\fBlqr_carver_get_col_depth\fR\&.
.SH "SEE ALSO"
.PP

\fBlqr_carver_new\fR(3), \fBlqr_carver_get_col_depth\fR(3), \fBlqr_carver_scan\fR(3), \fBlqr_carver_scan_line\fR(3)
.SH "COPYRIGHT"
Copyright \(co 2007-2009 Carlo Baldassi
.br
